// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhXmue3pHvnSA9Z2MGpYnbKxGuNMolJvc',
    appId: '1:451193617950:web:17f1e522bf57b8234b780f',
    messagingSenderId: '451193617950',
    projectId: 'flutter-modern-login-ui',
    authDomain: 'flutter-modern-login-ui.firebaseapp.com',
    storageBucket: 'flutter-modern-login-ui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrEA1w_HjJEejFSZZcPBUeKyeONlmO-2I',
    appId: '1:451193617950:android:75daf948edf6621a4b780f',
    messagingSenderId: '451193617950',
    projectId: 'flutter-modern-login-ui',
    storageBucket: 'flutter-modern-login-ui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0ykJjHdPGM93tZvflbKSKFgyaTppUT-Y',
    appId: '1:451193617950:ios:b14b5e51d340f4294b780f',
    messagingSenderId: '451193617950',
    projectId: 'flutter-modern-login-ui',
    storageBucket: 'flutter-modern-login-ui.appspot.com',
    iosClientId: '451193617950-nd09mh0u8sivu5coeh3t1o85fhimc1mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0ykJjHdPGM93tZvflbKSKFgyaTppUT-Y',
    appId: '1:451193617950:ios:14602ddd815ba5db4b780f',
    messagingSenderId: '451193617950',
    projectId: 'flutter-modern-login-ui',
    storageBucket: 'flutter-modern-login-ui.appspot.com',
    iosClientId: '451193617950-t94qdkc0rt12s30urajn1mb0ncqrgha9.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPages.RunnerTests',
  );
}
